text_offset = 0
text_size = 0xDC0
text_address = 0x04001080
rom_file_path = "aspboot.text.bin"
output_file_path = "rsp/aspMain.cpp"
output_function_name = "aspMain"

# VERSION_US
extra_indirect_branch_targets = [
    0x1118, 0x1470, 0x11DC, 0x1B38, 0x1214,
    0x187C, 0x1254, 0x12D0, 0x12EC, 0x1328,
    0x140C, 0x1294, 0x1DC8, 0x138C, 0x170C,
    0x144C
]

